class Test4
{
	public static void main(String... s)
	{
		try
		{
			
		}
		catch(ArithmeticException e)
		{

		}
		System.out.println("Hello");
		catch(Exception e)
		{
			
		}
		finally 
		{
			try
			{
				
			}
			catch(Exception e)
			{
				
			}
		
		}
	}
}